name: Build Binaries

on:
  push:
    tags:
      - "v*.*.*"   # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build rfir-lm (CLI tool)
        run: |
          echo "Building rfir-lm..."
          python -m nuitka --onefile --output-filename=security_questionnaire_responder security_questionnaire_responder.py
          echo "security_questionnaire_responder.py build completed."


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            security_questionnaire_responder*
