name: Build and Release Binaries

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      NUITKA_USE_DEPENDENCY_WALKER: "yes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka zstandard

      - name: Build rfir-lm (CLI tool)
        run: |
          python -m nuitka --onefile --enable-plugin=tk-inter --include-package=config --include-data-files=config.json.sample=config.json.sample --output-dir=dist security_questionnaire_responder.py
          echo "security_questionnaire_responder build completed."

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            security_questionnaire_responder*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from all OS builds
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: "Automated release of security_questionnaire_responder binaries."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/security_questionnaire_responder*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
