name: Build Binaries

on:
  push:
    tags:
      - "v*.*.*"   # Build on version tags like v1.0.0
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build rfir-lm (CLI tool)
        run: |
          python -m nuitka --onefile --standalone --output-filename=rfir-lm rfir-lm.py

      - name: Build rfir-web-front-end (Flask web UI)
        run: |
          python -m nuitka --onefile --standalone --output-filename=rfir-web-front-end app.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            rfir-lm*
            rfir-web-front-end*
